spring:
  application:
    name: toures-balon-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github:com/clickerclass/configserver-properties
          basedir: target/config
server:
  port: 8888